---
name: Validate Shell Scripts
on:
  pull_request:
    paths:
      - '**.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          #!/bin/bash
          set -e
          
          echo "Running ShellCheck on all shell scripts..."
          
          find . -name "*.sh" -type f | while read -r file; do
            echo "Checking: $file"
            shellcheck "$file"
          done
          
          echo "All shell scripts passed ShellCheck!"
